quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:catalogo}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/catalogo}

quarkus.flyway.migrate-at-start=true
